### ISSUE TITLE
Codigo-Error-Sopa de letras

### ISSUE THREAD

**Issue by Dunia30** [NILGroup/TFG-22-23-AdaptaMaterialEscolar2.0#27]
- [x] Si pones 1000 tanto en numero de columnas como de filas o en las dos la pagina peta, no responde.
- [x] Al añadir la sopa de letras en el editable y posicionarme después del enunciado y doy enter, se me crean tantas sopas de letras como veces de al enter.
- [x] Si pongo 3 numero para la filas o las columnas, por ejemplo 300, solo puedo ver los dos primeros números.

**Comment by AGomezSittima** [comment]
He limitado el numero de columnas y filas  a 20, por espacio y por rendimiento
Es necesario un elemetno Tabla para el documento de trabajo, he hecho un cambio temporal para que funcione mejor en el documento de trabajo
