### ISSUE TITLE
Codigo-Error-Relacionar conceptos

### ISSUE THREAD

**Issue by Dunia30** [NILGroup/TFG-22-23-AdaptaMaterialEscolar2.0#46]
- [x] Cuando creas una tabla  de las dimensiones que sean  y escribes dos conceptos en la misma columna se activa reordenar y el botón de OK 
- [ ] Por que el reordenar a veces solo me reordena una de las columnas y otras veces me reordena todas 
- [x] Si en una celda pongo espacios me lo da como bueno y se pone un puntito

**Comment by johansalgut** [comment]
**Por que el reordenar a veces solo me reordena una de las columnas y otras veces me reordena todas:**

Porque si reordenaramos simpre las dos columnas tendríamos este problema, imaginate  X = [x1, x2]  e Y = [y1, y2]. 
Si el reordenar se ejecutara siempre en ambas tendriamos solo X = [x1, x2]  e Y = [y1, y2] ó X = [x2, x1]  e Y = [y2  y1].
Nunca tendríamos el caso X = [x1, x2]  e Y = [y2, y1] ó X = [x2, x1]  e Y = [y1, y2]
